{% set name = "fancytypes" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fancytypes-{{ version }}.tar.gz
  sha256: 527f039973ed354966b316a16ef6ba0bc5185aaaca061b9f8fed6a2cbfbed7a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - czekitout

test:
  imports:
    - fancytypes
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/fancytypes/
  summary: Contains a base class representing an updatable parameter set that is equipped with methods to facilitate parameter data serialization and validation.
  dev_url: https://github.com/mrfitzpa/fancytypes
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
