{% set name = "fancytypes" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fancytypes-{{ version }}.tar.gz
  sha256: dbffeb5b59357dd6dc4d67b11f646910c3cca4b8ae97373c10fa868b013e290e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - czekitout

test:
  imports:
    - fancytypes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/fancytypes/
  summary: Contains a base class representing an updatable parameter set that is equipped with methods to facilitate parameter data serialization and validation.
  dev_url: https://github.com/mrfitzpa/fancytypes
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
