{% set name = "fancytypes" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fancytypes-{{ version }}.tar.gz
  sha256: 52b1118a2c56127a70ccc2c79fc1ea12580c17d36abf01eb9c62521d5b60854c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - czekitout

test:
  imports:
    - fancytypes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/fancytypes/
  summary: Contains a base class representing an updatable parameter set that is equipped with methods to facilitate parameter data serialization and validation.
  dev_url: https://github.com/mrfitzpa/fancytypes
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
